#used by jekyll-feed:- title, description,url,author
title: Dbugr
subtitle: Abhilash Panicker's portfolio
description: >- # this means to ignore newlines until "baseurl:"
  Dbugr is built on Jekyll, which is optimized for speed and readability.

url: "https://dbugr.netlify.app/" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog

google_analytics: G-NMS44KQWTW

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
    - text: Projects
      url: /projects
    - text: Contact
      url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

#image on the homepage
author_logo: abpanic.jpg
author: Abhilash Panicker
author_bio: Hi, my name is Abhilash. I am a data enthusiast, I love to talk about how data can make an impact. I am trying to put my findings to pen and paper with this site
author_email: "abhilash.panicker@outlook.com"
author_location: Bangalore, India
author_website_url: "https://dbugr.netlify.app/"
typewrite-text: Dbugr is built on jekyll framework. Review, comment and share blogs about debugging , tutorials and projects.
#background homepage cpover at /assets/img
hero_cover_img: sample_cover.jpg 

# Experiences
author_work_experiences:
            - company_name: Microsoft
              company_logo: Microsoft_logo.svg
              company_url: https://microsoft.com/
              designation: Partner Technical Advisor
              description: Working on Digital Transformation Platform/Dynamics 365 CE
              visibility: true

            - company_name: Wipro
              company_logo: Wipro.svg
              company_url: https://www.wipro.com/
              designation: Consultant
              description: Worked on Data Engineering projects
              visibility: true

            - company_name: IKS Health(formerly Inventurus Knowledge Solution)
              company_logo: IKSHealth.png
              company_url: https://www.ikshealth.com/
              designation: Technical Associate
              description: Worked on Data Engineering and Web Development projects
              visibility: true

            - company_name: Sitel
              company_logo: sitel.jpg
              company_url: https://www.sitel.com/
              designation: SQL Technical Customer Care Professional
              description: Troublshooting/Debugging and advisory on MS SQL issues
              visibility: true

# Education
author_education_details:
              - college_logo: UC_Boulder_logo.svg
                college_name: University of Colorado Boulder
                college_url: https://www.colorado.edu/
                college_degree: M.S.
                description: Specialization - DataScience
                visibility: true

              - college_logo: jnu-logo.png
                college_name: Jaipur National University
                college_url: https://www.jnujaipur.ac.in/
                college_degree: Bachelor of Computer Applications
                description: Bachelor of Computer Applications
                visibility: true

              - college_logo: IIT_Madras_Logo.svg
                college_name: Indian Institue of Technology, Madras
                college_url: https://eportfolio.mygreatlearning.com/abhilash-panicker
                college_degree: Advanced Certification in Software Engineering for Cloud, Blockchain & IoT
                description: Certification with hand-on academic Projects(https://eportfolio.mygreatlearning.com/abhilash-panicker)
                visibility: true

                



# Projects
author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Case Assist Portal
                project_description: One stop shop for all Case Management tasks
                project_url: https://msftcasehandling.azurewebsites.net/
                visibility: true
              - project_thumbnail: gamershub.png
                project_title: Weather Management
                project_description: A portal that has Distributed System to handle immense workload while splitting out traffic amongst the servers
                project_url: 
                visibility: true
#Badges
credly_details:
              - credlyid: abhilash-panicker
                badge_name: Microsoft Certified Trainer 2022-2023
                badge_id: 90a3d6b2-1dad-4027-8979-1d6f9f222588
                description: Demonstrate and maintain technical and instructional expertise on Microsoft technologies and who have complied with all requirements.
                visibility: true
              
              - credlyid: abhilash-panicker
                badge_name: Cloud Core
                badge_id: a4788b8d-646c-482b-9b00-2f9c6e63bd92
                description: Familiar with essentials of cloud applications and terms like Virtualization, VMs, Containers, Object Storage, Microservices, Serverless, Cloud Native, and DevOps
                visibility: true

#configuring the Atom feed
feed:
  categories:
    - news
    - updates
# social links
github_username:  abpanic
linkedin_username: abhilash-panicker-68952b159
medium_username: abpanic


#wakatime username (coding activity)
wakatime_username: abpanic

# mailchimp embedded form url (newsletter):
#mailchimp_form_url: 

# contact form - (choose formspress or getform)
getform_endpoint: 0c3a340e-bf4c-47c2-86ce-e7ba6e89a359
#formspree_endpoint: xyyvnzaq

# releases - widget can be (sidebar, modal or embed)
#olvy_organization: Dbugr
#olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
#paginate: nil
#paginate_path: nil
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"
# Pagination Settings
#pagination:
#  enabled: true
#  per_page: 4
#  paginate_path: "/blog/page/:num/"
#  permalink: '/blog/page/:num/'
#  title: ' - page :num'
#  limit: 0
#  sort_field: 'date'
#  sort_reverse: true


collections:
  authors:
    output: true
  projects:
    output: true
#  blogs:
#    output: true
#    permalink: /blog/:path/



defaults:
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  #- jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap

#exclude:
#  - .sass-cache/
#  - .jekyll-cache/
#  - gemfiles/
#  - Gemfile
#  - Gemfile.lock
#  - node_modules/
#  - vendor/bundle/
#  - vendor/cache/
#  - vendor/gems/
#  - vendor/ruby/



destination: ./build
