title: Dbugr
subtitle: A Portfolio Jekyll Theme Built for Programmers
description: >- # this means to ignore newlines until "baseurl:"
  Dbugr is built on Jekyll, which is optimized for speed and readability.

url: "https://dbugr.netlify.app/" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
    - text: Projects
      url: /projects
    - text: Contact
      url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: abpanic.jpg
author: Abhilash Panicker
author_bio: Hi, my name is Abhilash. I built this site using jekyll :D
author_email: "abhilash.panicker@outlook.com"
author_location: Bangalore, India
author_website_url: "https://dbugr.netlify.app/"
typewrite-text: Dbugr is built on jekyll framework. Review, comment and share blogs about debugging , tutorials. 
hero_cover_img: sample_cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: Microsoft
              company_logo: microsoft.png
              company_url: https://microsoft.com/
              designation: Partner Technical Advisor
              description: Worked on Digital Transformation Platform
              visibility: true

            - company_name: Wipro
              company_logo: Wipro.svg
              company_url: https://www.wipro.com/
              designation: Consultant
              description: Worked on various Azure Cloud Products
              visibility: true

            - company_name: IKS Health(formerly Inventurus Knowledge Solution)
              company_logo: IKSHealth.png
              company_url: https://www.ikshealth.com/
              designation: Technical Associate
              description: Data Engineer
              visibility: true

            - company_name: Sitel
              company_logo: sitel.jpg
              company_url: https://www.sitel.com/
              designation: CCR
              description: SQL
              visibility: true

# Education
author_education_details:
              - college_logo: jnu-logo.png
                college_name: University of Colorado Boulder
                college_url: https://www.colorado.edu/
                college_degree: Master of Science
                description: DataScience
                visibility: true
              - college_logo: jnu-logo.png
                college_name: Jaipur National University
                college_url: https://www.jnujaipur.ac.in/
                college_degree: Bachelor of Computer Applications
                description: Bachelor of Computer Applications
                visibility: true



# Projects
author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: false
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: false
#Badges
#Credly: abhilash-panicker

# social links
#twitter_username: johndoe
github_username:  abpanic
#facebook_username: johndoe
#linkedin_username: johndoe
#behance_username: johndoe
#instagram_username: johndoe
#medium_username: johndoe
#telegram_username: johndoe
#dribbble_username: johndoe
#flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: 
#hyvor_talk_website_id: 

#wakatime username (coding activity)
wakatime_username: abpanic

# mailchimp embedded form url (newsletter):
#mailchimp_form_url: 

# contact form - (choose formspress or getform)
getform_endpoint: 0c3a340e-bf4c-47c2-86ce-e7ba6e89a359
#formspree_endpoint: xyyvnzaq

# releases - widget can be (sidebar, modal or embed)
olvy_organization: Dbugr
olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"


# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: false
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
#  - jekyll-admin

# Jekyll Admin Config
#jekyll_admin:
#   hidden_links:
#     - posts
#     - pages
#     - staticfiles
#     - datafiles
#     - configuration
#homepage: "posts"


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
#gh-pages - For Github Pages
# firebase - For Firebase Hosting

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - assets/bower_components/isotope-layout/README.md
  - assets/bower_components/icono/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
  - assets/bower_components/ghosthunter/README.md
  - assets/bower_components/nanobar/README.md
  - assets/bower_components/lightgallery/demo/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
  - assets/bower_components/jquery-mousewheel/README.md
  - assets/bower_components/get-size/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
  - assets/bower_components/desandro-matches-selector/README.md
  - assets/bower_components/ev-emitter/README.md
  - assets/bower_components/font-awesome/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
  - assets/bower_components/ghosthunter/example/Index.html
  - assets/bower_components/lightgallery/test/lightgallery.html
  - assets/bower_components/masonry-layout/README.md
  - assets/bower_components/imagesloaded/README.md


destination: ./build
