#used by jekyll-feed:- title, description,url,author
title: Dbugr
subtitle: Abhilash Panicker's portfolio
description: >- # this means to ignore newlines until "baseurl:"
  Dbugr is built on Jekyll, which is optimized for speed and readability.

url: "https://dbugr.netlify.app/" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog

google_analytics: G-NMS44KQWTW

# Navigation
urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blog
      url: /blog
    - text: Projects
      url: /projects
    - text: Contact
      url : /contact


# Edit Author details (For multi authors check _data/authors.yml)

#image on the homepage
author_logo: abpanic.jpg
author: Abhilash Panicker
author_bio: Hi, my name is Abhilash. I am a data enthusiast, I love to talk about how data can make an impact. I am trying to put my findings to pen and paper with this site
author_email: "abhilash.panicker@outlook.com"
author_location: Bangalore, India
author_website_url: "https://dbugr.netlify.app/"
typewrite-text: Dbugr is built on jekyll framework. Review, comment and share blogs about debugging , tutorials and projects.
#background homepage cpover at /assets/img
hero_cover_img: sample_cover.jpg 

# Experiences
author_work_experiences:
            - company_name: Microsoft
              company_logo: Microsoft_logo.svg
              company_url: https://microsoft.com/
              designation: Partner Technical Advisor
              description: Working on Digital Transformation Platform/Dynamics 365 CE
              visibility: true

            - company_name: Wipro
              company_logo: Wipro.svg
              company_url: https://www.wipro.com/
              designation: Consultant
              description: Worked on Data Engineering projects
              visibility: true

            - company_name: IKS Health(formerly Inventurus Knowledge Solution)
              company_logo: IKSHealth.png
              company_url: https://www.ikshealth.com/
              designation: Technical Associate
              description: Worked on Data Engineering and Web Development projects
              visibility: true

            - company_name: Sitel
              company_logo: sitel.jpg
              company_url: https://www.sitel.com/
              designation: SQL Technical Customer Care Professional
              description:
              visibility: true

# Education
author_education_details:
              - college_logo: University-of-Colorado-Boulder-Logo.png
                college_name: University of Colorado Boulder
                college_url: https://www.colorado.edu/
                college_degree: Master of Science
                description: DataScience(Specialization)
                visibility: true

              - college_logo: jnu-logo.png
                college_name: Jaipur National University
                college_url: https://www.jnujaipur.ac.in/
                college_degree: Bachelor of Computer Applications
                description: Bachelor of Computer Applications
                visibility: true

              - college_logo: jnu-logo.png
                college_name: Indian Institue of Technology, Madras
                college_url: https://eportfolio.mygreatlearning.com/abhilash-panicker
                college_degree: Advanced Certification in Software Engineering for Cloud, Blockchain & IoT
                description: Certification with hand-on academic Projects(https://eportfolio.mygreatlearning.com/abhilash-panicker)
                visibility: true

                



# Projects
author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Case Assist Portal
                project_description: One stop shop for all Case Management tasks
                project_url: https://msftcasehandling.azurewebsites.net/
                visibility: true
              - project_thumbnail: gamershub.png
                project_title: Weather Management
                project_description: A portal that has Distributed System to handle immense workload while splitting out traffic amongst the servers
                project_url: 
                visibility: true
#Badges
#Credly: abhilash-panicker

#configuring the Atom food
feed:
  categories:
    - news
    - updates
# social links
#twitter_username: johndoe
github_username:  abpanic
#facebook_username: johndoe
#linkedin_username: johndoe
#behance_username: johndoe
#instagram_username: johndoe
#medium_username: johndoe
#telegram_username: johndoe
#dribbble_username: johndoe
#flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: 
#hyvor_talk_website_id: 

#wakatime username (coding activity)
wakatime_username: abpanic

# mailchimp embedded form url (newsletter):
#mailchimp_form_url: 

# contact form - (choose formspress or getform)
getform_endpoint: 0c3a340e-bf4c-47c2-86ce-e7ba6e89a359
#formspree_endpoint: xyyvnzaq

# releases - widget can be (sidebar, modal or embed)
#olvy_organization: Dbugr
#olvy_widget_type: sidebar

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
#paginate: nil
#paginate_path: nil
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"
# Pagination Settings
#pagination:
#  enabled: true
#  per_page: 4
#  paginate_path: "/blog/page/:num/"
#  permalink: '/blog/page/:num/'
#  title: ' - page :num'
#  limit: 0
#  sort_field: 'date'
#  sort_reverse: true


collections:
  authors:
    output: true
  projects:
    output: true
#  blogs:
#    output: true
#    permalink: /blog/:path/



defaults:
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug
  -
    scope:
      path: 'assets/**'
    values:
      sitemap: false

# Build settings
plugins:
  #- jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

### Switching Deployment Strategy (in DEPLOY_STRATEGY) file change the key accordingly:
# none - For no default
#gh-pages - For Github Pages
# firebase - For Firebase Hosting

#exclude:
#  - .sass-cache/
#  - .jekyll-cache/
#  - gemfiles/
#  - Gemfile
#  - Gemfile.lock
#  - node_modules/
#  - vendor/bundle/
#  - vendor/cache/
#  - vendor/gems/
#  - vendor/ruby/
#  - assets/bower_components/isotope-layout/README.md
#  - assets/bower_components/icono/README.md
#  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-svg-core/README.md
#  - assets/bower_components/ghosthunter/README.md
#  - assets/bower_components/nanobar/README.md
#  - assets/bower_components/lightgallery/demo/README.md
#  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-brands-svg-icons/README.md
#  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/free-solid-svg-icons/README.md
#  - assets/bower_components/jquery-mousewheel/README.md
#  - assets/bower_components/get-size/README.md
#  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome/README.md
#  - assets/bower_components/jquery-mousewheel/ChangeLog/README.md
#  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-regular/README.md
#  - assets/bower_components/desandro-matches-selector/README.md
#  - assets/bower_components/ev-emitter/README.md
#  - assets/bower_components/font-awesome/README.md
#  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-solid/README.md
#  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free/README.md
#  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-webfonts/README.md
#  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-free-brands/README.md
#  - assets/bower_components/font-awesome/advanced-options/use-with-node-js/fontawesome-common-types/README.md
#  - assets/bower_components/ghosthunter/example/Index.html
#  - assets/bower_components/lightgallery/test/lightgallery.html
#  - assets/bower_components/masonry-layout/README.md
#  - assets/bower_components/imagesloaded/README.md


destination: ./build
